######################################################################
# Automatically generated by qmake (2.01a) ? 10? 14 21:35:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h tabletapplication.h tabletcanvas.h
SOURCES += main.cpp mainwindow.cpp tabletapplication.cpp tabletcanvas.cpp
